env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  BUILDKIT_PROGRESS: "plain"
  NO_SQUASH: ""
  NO_SILENT: "1"
  NONINTERACTIVE: "1"
  FORCE_ONLINE: "1"
  NBPARALLEL: "2"
  RELEASABLE_REPOS: "^corpusops/"
  RELEASABLE_BRANCHES: "^(refs/heads/)?(master|main|2.0|workflows)$"
  COPS_URL: "https://github.com/corpusops/corpusops.bootstrap"
  COPS_ROOT: "${{github.workspace}}/local/corpusops.bootstrap"
  silent: "$COPS_ROOT/bin/cops_shell_common output_in_error silent_vv"
  DOCKER_RELEASER: "${{ secrets.DOCKER_HUB_USERNAME }}"
  DOCKER_PASSWORD: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
jobs:
  r:
    runs-on: ubuntu-20.04
    env: {IMAGES: "${{matrix.IMAGES}}"}
    steps:
      - name: Set vars
        run: |-
            if ( echo "$GITHUB_REF" | egrep -q "${RELEASABLE_BRANCHES}" ) \
            && ( echo "$GITHUB_REPOSITORY" | egrep -q "${RELEASABLE_REPOS}" )
            then releasable=true;else releasable=false;fi
            echo "releasable=$releasable" >> $GITHUB_OUTPUT
            echo "silent=$(echo $silent)" >> $GITHUB_OUTPUT
        id: v
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Activate docker experimental
        run: |-
          sudo bash -exc "service docker stop;python -c \
          \"d='/etc/docker/daemon.json';\
          import json;c=json.load(open(d));c['experimental']=True;\
          open(d, 'w').write(json.dumps(c))\"
          systemctl restart docker"
      - uses: actions/checkout@v3
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            local
          key: 6-${{ runner.os }}-${{ github.ref }}-${{ github.repository }}-venvstatics
      - name: setup
        run: set -e;i=$(whoami);sudo sh -c "chown -Rf $i .";
             sudo sh -c 'sed -i -re 's/azure.//' /etc/apt/sources.list && apt-get update -qq' && ./main.sh refresh_corpusops;
             sudo sh -c 'sed -i -re 's/azure.//' /etc/apt/sources.list && apt-get update -qq && apt-get install -qqy --force-yes parallel'
      - name: refresh images
        run: set -e;if (echo $IMAGES|grep -q zleftover);then
             rm -f */*/*/Dockerfile&&${{steps.v.outputs.silent}} ./refresh_images.sh;
             fi
      - name: build & release
        run: set -e;
             if [ "x${{steps.v.outputs.releasable}}" = "xtrue" ];then export DO_RELEASE=1;fi;
             ./build.sh $IMAGES
# ${{steps.v.outputs.silent}} ./build.sh $IMAGES
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        IMAGES:
        - "library/php/8 library/php/8-alpine library/php/8-apache library/php/8-cli library/php/8-cli-alpine library/php/8-fpm library/php/8-fpm-alpine library/php/8-zts"
        - "library/php/7.4 library/php/7.4-alpine library/php/7.4-apache library/php/7.4-cli library/php/7.4-cli-alpine library/php/7.4-fpm library/php/7.4-fpm-alpine library/php/7.4-rc library/php/7.4-zts library/php/7.4-zts-alpine"
        - "library/php/7.3 library/php/7.3-alpine library/php/7.3-apache library/php/7.3-cli library/php/7.3-cli-alpine library/php/7.3-fpm library/php/7.3-fpm-alpine library/php/7.3-rc library/php/7.3-zts library/php/7.3-zts-alpine"
        - "library/php/7.2 library/php/7.2-alpine library/php/7.2-apache library/php/7.2-cli library/php/7.2-cli-alpine library/php/7.2-fpm library/php/7.2-fpm-alpine library/php/7.2-rc library/php/7.2-zts"
        - "library/php/7.1 library/php/7.1-alpine library/php/7.1-apache library/php/7.1-cli library/php/7.1-cli-alpine library/php/7.1-fpm library/php/7.1-fpm-alpine library/php/7.1-rc library/php/7.1-zts library/php/7.1-zts-alpine"
        - "library/php/8.0 library/php/8.0-alpine library/php/8.0-apache library/php/8.0-cli library/php/8.0-cli-alpine library/php/8.0-fpm library/php/8.0-fpm-alpine library/php/8.0-rc library/php/8.0-zts"
        - "library/php/7 library/php/7-alpine library/php/7-apache library/php/7-cli library/php/7-cli-alpine library/php/7-fpm library/php/7-fpm-alpine library/php/7-zts library/php/7-zts-alpine"
        - "library/php/5 library/php/5-alpine library/php/5-apache library/php/5-cli library/php/5-cli-alpine library/php/5-fpm library/php/5-fpm-alpine library/php/5-zts library/php/5-zts-alpine"
        - "library/php/latest library/php/alpine library/php/apache library/php/cli library/php/cli-alpine library/php/fpm library/php/fpm-alpine library/php/zts library/php/zts-alpine"
        #- "corpusops/test/a corpusops/test/b corpusops/test/c"
        # all images that werent explicitly told to be built would be built in the next batches
        # we span them onto N jobs
        - "zleftover:1/14"
        - "zleftover:2/14"
        - "zleftover:3/14"
        - "zleftover:4/14"
        - "zleftover:5/14"
        - "zleftover:6/14"
        - "zleftover:7/14"
        - "zleftover:8/14"
        - "zleftover:9/14"
        - "zleftover:10/14"
        - "zleftover:11/14"
        - "zleftover:12/14"
        - "zleftover:13/14"
        - "zleftover:14/14"
on:
  push:
  workflow_dispatch:
  schedule: [{cron: '1 0 4,6,8,18,20,22 * *'}]
